# Generated by Django 5.2 on 2026-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0006_recurring_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_expenses',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
